ERROR | 2022-10-10 12:06:09,576 | main.py:39 | BOT WAS STARTED
NoneType: None
ERROR | 2022-10-10 12:08:03,388 | z_all_errors.py:21 | Exception: Message text is empty
Update: {"update_id": 46689436, "message": {"message_id": 2755, "from": {"id": 1144427229, "is_bot": false, "first_name": "dastan", "username": "dast4nkg", "language_code": "ru"}, "chat": {"id": 1144427229, "first_name": "dastan", "username": "dast4nkg", "type": "private"}, "date": 1665382082, "text": "üì• –¢—Ä–∞–Ω—Å–∫—Ä–∏–ø—Ç"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 152, in user_profile
    await message.answer(text)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 397, in answer
    return await self.bot.send_message(
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 341, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageTextIsEmpty: Message text is empty
ERROR | 2022-10-10 12:08:03,401 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-34' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageTextIsEmpty('Message text is empty')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 152, in user_profile
    await message.answer(text)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 397, in answer
    return await self.bot.send_message(
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 341, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageTextIsEmpty: Message text is empty
ERROR | 2022-10-10 12:08:19,983 | z_all_errors.py:21 | Exception: Message text is empty
Update: {"update_id": 46689438, "message": {"message_id": 2758, "from": {"id": 1144427229, "is_bot": false, "first_name": "dastan", "username": "dast4nkg", "language_code": "ru"}, "chat": {"id": 1144427229, "first_name": "dastan", "username": "dast4nkg", "type": "private"}, "date": 1665382099, "text": "üì• –¢—Ä–∞–Ω—Å–∫—Ä–∏–ø—Ç"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 152, in user_profile
    await message.answer(text)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 397, in answer
    return await self.bot.send_message(
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 341, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageTextIsEmpty: Message text is empty
ERROR | 2022-10-10 12:08:19,983 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-42' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageTextIsEmpty('Message text is empty')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 152, in user_profile
    await message.answer(text)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 397, in answer
    return await self.bot.send_message(
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 341, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageTextIsEmpty: Message text is empty
ERROR | 2022-10-10 12:09:27,927 | z_all_errors.py:21 | Exception: Message text is empty
Update: {"update_id": 46689439, "message": {"message_id": 2759, "from": {"id": 1144427229, "is_bot": false, "first_name": "dastan", "username": "dast4nkg", "language_code": "ru"}, "chat": {"id": 1144427229, "first_name": "dastan", "username": "dast4nkg", "type": "private"}, "date": 1665382166, "text": "üì• –¢—Ä–∞–Ω—Å–∫—Ä–∏–ø—Ç"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 152, in user_profile
    await message.answer(text)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 397, in answer
    return await self.bot.send_message(
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 341, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageTextIsEmpty: Message text is empty
ERROR | 2022-10-10 12:09:27,928 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-49' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=MessageTextIsEmpty('Message text is empty')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 152, in user_profile
    await message.answer(text)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/types/message.py", line 397, in answer
    return await self.bot.send_message(
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 341, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageTextIsEmpty: Message text is empty
ERROR | 2022-10-10 12:09:40,655 | z_all_errors.py:21 | Exception: list index out of range
Update: {"update_id": 46689441, "callback_query": {"id": "4915277523378315594", "from": {"id": 1144427229, "is_bot": false, "first_name": "dastan", "username": "dast4nkg", "language_code": "ru"}, "message": {"message_id": 2761, "from": {"id": 5366267602, "is_bot": true, "first_name": "eBilim", "username": "ebilim_bot"}, "chat": {"id": 1144427229, "first_name": "dastan", "username": "dast4nkg", "type": "private"}, "date": 1665382169, "text": "–ü—Ä–µ–¥–º–µ—Ç—ã", "reply_markup": {"inline_keyboard": [[{"text": "–ü—Ä–∏–∫–ª–∞–¥–Ω–∞—è –º–∞—Ç–µ–º–∞—Ç–∏–∫–∞ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=418&year=22&session=1&idDis=14"}], [{"text": "–ë–∞–∑—ã –¥–∞–Ω–Ω—ã—Ö 1 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=419&year=22&session=1&idDis=15"}], [{"text": "–Ø–∑—ã–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è 3 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=420&year=22&session=1&idDis=16"}], [{"text": "–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ —Å–µ—Ç–∏ –∏ —Ç–µ–ª–µ–∫–æ–º–º—É–Ω–∏–∫–∞—Ü–∏–∏ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=421&year=22&session=1&idDis=26"}], [{"text": "–ù–µ–º–µ—Ü–∫–∏–π —è–∑—ã–∫ 3 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=422&year=22&session=1&idDis=18"}], [{"text": "–û—Å–Ω–æ–≤—ã –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏—Ö –Ω–∞—É–∫ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=423&year=22&session=1&idDis=21"}], [{"text": "–Ø–∑—ã–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è 3 -", "callback_data": "/StudentJurnal/course?planId=446&year=22&session=1&idDis=16"}]]}}, "chat_instance": "5860257382183580453", "data": "/StudentJurnal/course?planId=420&year=22&session=1&idDis=16"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 199, in insert_login
    text = f"–û—Ü–µ–Ω–∫–∏ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-10 12:09:40,656 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-58' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 199, in insert_login
    text = f"–û—Ü–µ–Ω–∫–∏ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-10 12:09:55,932 | z_all_errors.py:21 | Exception: list index out of range
Update: {"update_id": 46689443, "callback_query": {"id": "4915277523233296122", "from": {"id": 1144427229, "is_bot": false, "first_name": "dastan", "username": "dast4nkg", "language_code": "ru"}, "message": {"message_id": 2763, "from": {"id": 5366267602, "is_bot": true, "first_name": "eBilim", "username": "ebilim_bot"}, "chat": {"id": 1144427229, "first_name": "dastan", "username": "dast4nkg", "type": "private"}, "date": 1665382183, "text": "–ü—Ä–µ–¥–º–µ—Ç—ã", "reply_markup": {"inline_keyboard": [[{"text": "–ü—Ä–∏–∫–ª–∞–¥–Ω–∞—è –º–∞—Ç–µ–º–∞—Ç–∏–∫–∞ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=418&year=22&session=1&idDis=14"}], [{"text": "–ë–∞–∑—ã –¥–∞–Ω–Ω—ã—Ö 1 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=419&year=22&session=1&idDis=15"}], [{"text": "–Ø–∑—ã–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è 3 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=420&year=22&session=1&idDis=16"}], [{"text": "–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ —Å–µ—Ç–∏ –∏ —Ç–µ–ª–µ–∫–æ–º–º—É–Ω–∏–∫–∞—Ü–∏–∏ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=421&year=22&session=1&idDis=26"}], [{"text": "–ù–µ–º–µ—Ü–∫–∏–π —è–∑—ã–∫ 3 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=422&year=22&session=1&idDis=18"}], [{"text": "–û—Å–Ω–æ–≤—ã –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏—Ö –Ω–∞—É–∫ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=423&year=22&session=1&idDis=21"}], [{"text": "–Ø–∑—ã–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è 3 -", "callback_data": "/StudentJurnal/course?planId=446&year=22&session=1&idDis=16"}]]}}, "chat_instance": "5860257382183580453", "data": "/StudentJurnal/course?planId=420&year=22&session=1&idDis=16"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 199, in insert_login
    text = f"–û—Ü–µ–Ω–∫–∏ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-10 12:09:55,933 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-66' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 199, in insert_login
    text = f"–û—Ü–µ–Ω–∫–∏ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-10 12:10:25,446 | z_all_errors.py:21 | Exception: list index out of range
Update: {"update_id": 46689446, "callback_query": {"id": "4915277523313724022", "from": {"id": 1144427229, "is_bot": false, "first_name": "dastan", "username": "dast4nkg", "language_code": "ru"}, "message": {"message_id": 2767, "from": {"id": 5366267602, "is_bot": true, "first_name": "eBilim", "username": "ebilim_bot"}, "chat": {"id": 1144427229, "first_name": "dastan", "username": "dast4nkg", "type": "private"}, "date": 1665382218, "text": "–ü—Ä–µ–¥–º–µ—Ç—ã", "reply_markup": {"inline_keyboard": [[{"text": "–ü—Ä–∏–∫–ª–∞–¥–Ω–∞—è –º–∞—Ç–µ–º–∞—Ç–∏–∫–∞ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=418&year=22&session=1&idDis=14"}], [{"text": "–ë–∞–∑—ã –¥–∞–Ω–Ω—ã—Ö 1 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=419&year=22&session=1&idDis=15"}], [{"text": "–Ø–∑—ã–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è 3 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=420&year=22&session=1&idDis=16"}], [{"text": "–ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ —Å–µ—Ç–∏ –∏ —Ç–µ–ª–µ–∫–æ–º–º—É–Ω–∏–∫–∞—Ü–∏–∏ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=421&year=22&session=1&idDis=26"}], [{"text": "–ù–µ–º–µ—Ü–∫–∏–π —è–∑—ã–∫ 3 –Ω/—É", "callback_data": "/StudentJurnal/course?planId=422&year=22&session=1&idDis=18"}], [{"text": "–û—Å–Ω–æ–≤—ã –º–µ–¥–∏—Ü–∏–Ω—Å–∫–∏—Ö –Ω–∞—É–∫ –Ω/—É", "callback_data": "/StudentJurnal/course?planId=423&year=22&session=1&idDis=21"}], [{"text": "–Ø–∑—ã–∫–∏ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Ä–æ–≤–∞–Ω–∏—è 3 -", "callback_data": "/StudentJurnal/course?planId=446&year=22&session=1&idDis=16"}]]}}, "chat_instance": "5860257382183580453", "data": "/StudentJurnal/course?planId=422&year=22&session=1&idDis=18"}}
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 199, in insert_login
    text = f"–û—Ü–µ–Ω–∫–∏ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
ERROR | 2022-10-10 12:10:25,446 | base_events.py:1744 | Task exception was never retrieved
future: <Task finished name='Task-80' coro=<Dispatcher._process_polling_updates() done, defined at /home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/niko/Documents/EBilim-v2/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/niko/Documents/EBilim-v2/handlers/user.py", line 199, in insert_login
    text = f"–û—Ü–µ–Ω–∫–∏ –ø–æ –ø—Ä–µ–¥–º–µ—Ç—É: <code>{subject[14]}</code>\n" \
IndexError: list index out of range
